name: 'Build and Push Worker image'

on:
  push:
    branches:
      - "main"
    paths:
      - ./worker/**.go
      - ./worker/Dockerfile
      - ./worker/go.mod
      - ./worker/go.sum
  workflow_dispatch: {}

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Login to GCR'
        uses: 'docker/login-action@v2'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v2'

      - name: Image meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            gcr.io/superhub/stacks-disposer-worker
          tags: |
            type=raw,value=latest
            type=sha,prefix=

      - name: 'Build and push'
        uses: "docker/build-push-action@v3"
        with:
          context: ./worker
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
